### ISSUE TITLE
Add lint to travisCI text

### ISSUE THREAD

**Issue by andreww** [katyhuff/python-testing#10]
I taught this lesson yesterday as part of a more-advanced SWC workshop for 30. It's great! While I remember one common problem the students hit in the Continuous Integration part is that travisCI is _very_ picky about the format of the `.travis.yaml` file. It's probably worth adding a note about this either in the lesson or in the instructor notes. 

A useful tool to point to would be the travis.yaml linter at https://lint.travis-ci.org/ and maybe note some common error cases somewhere. These seem to be:

* .travis.yaml is malformed. There is an error message at the top of the job log, and pointing to the linter is probably the best plan.
* the tests fail and end with a message about "rake". This is an attempt to run tests for Ruby (the default case for Travis) and this probably means that the `.travis.yaml` has not been found. A common reason seems to be that people forget the first dot at the start of the filename. The fix is to rename (git mv ..., git commit, git push) and try again.
* the tests don't run. This happens if the student adds the files and commits them before turning on tests for the repository in travis (I think there is a bit of a delay between linking the travis and github account and being able to do anything, so if the student moves on to keep up they may do the push before flipping the switch in travis). The fix is to push some other change to the repo.

Anyway, I'll try to turn these into a pull request when I get a chance, but at least if I stick this here I'll not completely forget.

**Comment by katyhuff** [comment]
@andreww excellent!! I'm so glad it was useful to you. Noting to the linter is a great idea! If you have time to make a PR, that'll be great. If not, having an issue here will help me or someone else get to it eventually, so thanks for writing the issue!!

**Comment by andreww** [comment]
Finally found some time. Hopefully this is a sensible way to add the linter info.

**Comment by katyhuff** [comment]
I forgot to close this when we merged the fix. Thanks again.
