### ISSUE TITLE
template and styling 

### ISSUE THREAD

**Issue by dejmail** [katyhuff/python-testing#8]
Hi Katy

I have been in contact with Greg and Jonah from Software Carpentry, as I thought to present a Unit Testing course to the scientists in my region (and possibly punt your book!). They said that the course you have prepared is great, although suggested that I could contribute by bringing the template and styling up to date. Would you be ok with that ? Greg said he would be able to help me along with getting through what needs to be altered and that it shouldn't be a huge amount of work.

Sincerely
Liam

**Comment by katyhuff** [comment]
Of course! It would be great for you to take the time to do that! I'm
looking forward to the pull request! Please let me know if anything comes
up that I can help you with!

**Comment by dejmail** [comment]
Hi Katy

I've finally completed the transition to the updated styling and 
templating. Sorry it took so long ! I hope I did it correctly and 
haven't introduced typos or other errors. I received quite a bit of help 
from Greg Wilson, who it seems has now stepped down from his previous 
role at SWC.

- I have not managed to specify how much time to apportion to each 
lesson, perhaps you could help with that ?

- Also, how would one present the information in the lessons ? Do you 
construct some slides separately, or is this SWC template somehow 
presentable as is ?

Let me know if you have any questions.

Regards
Liam

**Comment by katyhuff** [comment]
@dejmail : there are conflicts in your PR, which means that you need to merge the main branch and resolve the conflicts again. Also, it seems like there were a lot of text-editor-induced line breaks that were committed as new changes. 

Regarding your two questions:
- I can help with adding time estimates. Let's just make that a separate issue, to be dealt with in a future PR. 
- As with all SWC lessons, the web template is intended to be used as the main presentation reference material, no slides are made, and the majority of the lesson is spent actively doing the exercises with the learners in the terminal or in the ipython notebooks.

**Comment by dejmail** [comment]
@katyhuff : Ok, I'll try it out. I saw it mentioned that there were conflicts, but as I've never done a PR before, wasn't quite sure what was going on. The line breaks, not sure where they came from...edited this in emacs although when I compiled the lesson it did seem to complain that there were alot of "lines that were too long". I'll do as you suggest, fix the first merge issue, and then I can tackle the remainder.

**Comment by katyhuff** [comment]
Thanks. Here's some info on merge conflicts: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

As far as the line breaks go, it's not a big deal.  It just makes the PR a little harder to review if there are a lot of changes that aren't really changes. If it was jekyll complaining about too-long lines, then it's fine to leave the new line breaks. Thanks!

**Comment by dejmail** [comment]
Ok thanks, I also looked at [http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository/7244456#7244456](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository/7244456#7244456). I was confused as hell but think I figured it out in the end.

You can merge if you're happy with the changes so far.

**Comment by katyhuff** [comment]
fixed with #12 ! Thanks @dejmail !
